import type { LevelDef } from '../sim/types';

export const LEVELS: readonly LevelDef[] = [
  {
    id: 'first-bounce',
    name: 'First Bounce',
    hint: 'Tap the orange mirror to turn it. Drag a mirror from the tray.',
    map: [
      '..........',
      '>..A.../..',
      '..........',
      '..........',
      '..........',
      '..........',
      '...B......',
      '..........',
      '..........',
      '..........',
    ],
    tray: { mirror: 1 },
  },
  {
    id: 'b-before-c',
    name: 'B Before C',
    hint: 'The light has to reach B before C.',
    map: [
      '......../.',
      '...B......',
      '..........',
      '........C.',
      '..........',
      '>.A...../.',
      '..........',
      '..........',
      '..........',
      '..........',
    ],
    tray: { mirror: 2 },
  },
  {
    id: 'zigzag',
    name: 'Zigzag',
    hint: 'Turn the fixed mirrors first, then fill the gaps.',
    map: [
      '..........',
      '........D.',
      '..........',
      '..........',
      '.\\..B.....',
      '..........',
      '..........',
      '.A./..C...',
      '..........',
      '.^........',
    ],
    tray: { mirror: 3 },
  },
  {
    id: 'split-beam',
    name: 'Split Beam',
    hint: 'The glass splitter sends light two ways. A block stops it.',
    map: [
      '....E.../.',
      '..........',
      '....B...D.',
      '..........',
      '>.A....C..',
      '..#....#..',
      '..........',
      '..#....#..',
      '..........',
      '..........',
    ],
    tray: { mirror: 1, splitter: 1, block: 1 },
  },
  {
    id: 'hall-of-mirrors',
    name: 'Hall of Mirrors',
    hint: 'Six stops. Plan the route before you place anything.',
    map: [
      'v.........',
      '...\\.E../.',
      'A.#.......',
      '......#.D.',
      '..........',
      '/..B......',
      '..........',
      '.....C.#..',
      '.#........',
      '.....F....',
    ],
    tray: { mirror: 3, splitter: 1, block: 1 },
  },
];
