import type { LevelDef } from '../sim/types';

export const LEVELS: readonly LevelDef[] = [
  {
    id: 'first-bounce',
    name: 'First Bounce',
    hint: 'Tap the fixed mirror to turn it. Drag a mirror from the tray.',
    map: [
      '..........',
      '>..A.../..',
      '..........',
      '..........',
      '..........',
      '..........',
      '...B......',
      '..........',
      '..........',
      '..........',
    ],
    tray: { mirror: 1 },
  },
  {
    id: 'b-before-c',
    name: 'B Before C',
    hint: 'The light has to reach B before C.',
    map: [
      '......../.',
      '...B......',
      '..........',
      '........C.',
      '..........',
      '>.A...../.',
      '..........',
      '..........',
      '..........',
      '..........',
    ],
    tray: { mirror: 2 },
  },
  {
    id: 'zigzag',
    name: 'Zigzag',
    hint: 'Turn the fixed mirrors first, then fill the gaps.',
    map: [
      '..........',
      '........D.',
      '..........',
      '..........',
      '.\\..B.....',
      '..........',
      '..........',
      '.A./..C...',
      '..........',
      '.^........',
    ],
    tray: { mirror: 3 },
  },
  {
    id: 'split-beam',
    name: 'Split Beam',
    hint: 'The glass splitter sends light two ways. A block stops it.',
    map: [
      '....E.../.',
      '..........',
      '....B...D.',
      '..........',
      '>.A....C..',
      '..#....#..',
      '..........',
      '..#....#..',
      '..........',
      '..........',
    ],
    tray: { mirror: 1, splitter: 1, block: 1 },
  },
  {
    id: 'hall-of-mirrors',
    name: 'Hall of Mirrors',
    hint: 'Six stops. Plan the route before you place anything.',
    map: [
      'v.........',
      '...\\.E../.',
      'A.#.......',
      '......#.D.',
      '..........',
      '/..B......',
      '..........',
      '.....C.#..',
      '.#........',
      '.....F....',
    ],
    tray: { mirror: 3, splitter: 1, block: 1 },
  },
  {
    id: 'detour',
    name: 'Detour',
    hint: 'Only four stops. Not every fixed mirror is on the way.',
    map: [
      '....##....',
      '.......\\..',
      '....C..\\..',
      '#..B.....#',
      '..#/......',
      '..........',
      '.....A..#.',
      '#........D',
      '......#...',
      '#....^#...',
    ],
    tray: { mirror: 3 },
  },
  {
    id: 'too-soon',
    name: 'Too Soon',
    hint: 'The easy way gets to E much too soon.',
    map: [
      '..........',
      '.....B....',
      '#..#...##.',
      '.....#....',
      '..A.......',
      '...#..C...',
      '>...\\D\\...',
      '....E.....',
      '......F.G.',
      '.\\........',
    ],
    tray: { mirror: 4 },
  },
  {
    id: 'shortcut',
    name: 'Shortcut',
    hint: 'B needs the light sooner than the long way can bring it.',
    map: [
      '......../.',
      '.........#',
      '..........',
      '.../.D.E..',
      '..#.......',
      '...\\C.#B..',
      '........##',
      '......A.<.',
      '..........',
      '..........',
    ],
    tray: { mirror: 2, splitter: 1, block: 1 },
  },
  {
    id: 'crossroads',
    name: 'Crossroads',
    hint: 'The light is allowed to cross its own path.',
    map: [
      '..........',
      '....#..F./',
      '.....\\..B.',
      '.......E..',
      '......#..C',
      '....A...D\\',
      '>./.#...#.',
      '..#.......',
      '.\\.......#',
      '.........#',
    ],
    tray: { mirror: 4 },
  },
  {
    id: 'head-start',
    name: 'Head Start',
    hint: 'Cut one branch before it gets ahead.',
    map: [
      '.#...#..E.',
      '.#.#.....D',
      '.......F..',
      '.........C',
      '..H...G\\..',
      '..#......#',
      '.#.....B..',
      '.....#A...',
      '...../.\\..',
      '#.....^...',
    ],
    tray: { mirror: 3, splitter: 1, block: 1 },
  },
  {
    id: 'side-door',
    name: 'Side Door',
    hint: 'Five stops, one way in. Split the light before it turns.',
    map: [
      '.......D.E',
      '...#..C...',
      '.#.\\...A##',
      '....../.B/',
      '..#.......',
      '.........#',
      '..#..#.\\.<',
      '.......#.#',
      '..........',
      '.....#....',
    ],
    tray: { mirror: 2, splitter: 1, block: 1 },
  },
  {
    id: 'long-way-round',
    name: 'Long Way Round',
    hint: 'Seven stops. The short way is never the right way.',
    map: [
      '.........G',
      '.......#..',
      '.C..B\\.#F.',
      '.......E//',
      '.D.\\..A..<',
      '......#...',
      '......#.#.',
      '..........',
      '....#.\\...',
      '..........',
    ],
    tray: { mirror: 5 },
  },
  {
    id: 'tangle',
    name: 'Tangle',
    hint: 'Seven fixed mirrors. Most of them are in the way.',
    map: [
      '###.....#.',
      '...B....#.',
      '.#.##.C.D\\',
      '#.....###E',
      '...\\./#...',
      '..\\.A./...',
      '>.....\\...',
      '...../....',
      '..........',
      '.#........',
    ],
    tray: { mirror: 3 },
  },
  {
    id: 'photo-finish',
    name: 'Photo Finish',
    hint: 'Two branches race. Only one of them may reach H.',
    map: [
      '>A\\.......',
      '#..../....',
      '..B.#.....',
      '......D...',
      '#.........',
      '..C.......',
      '...#.#.E.#',
      '..........',
      '..H/......',
      '..#.G.F...',
    ],
    tray: { mirror: 3, splitter: 1, block: 1 },
  },
  {
    id: 'last-light',
    name: 'Last Light',
    hint: 'Nine stops. Everything in the tray, all at once.',
    map: [
      '..........',
      '......#...',
      '....../...',
      '...#......',
      '.../\\.\\...',
      '.G.\\F...#.',
      'H.....B/#.',
      '....E...#.',
      'I....A.C..',
      '...^..D...',
    ],
    tray: { mirror: 4, splitter: 1, block: 1 },
  },
];
